### ISSUE TITLE
Key argument cannot be null

### ISSUE THREAD

**Issue by EbitFSE** [ministero-salute/it-fse-gtw-tools#6]
Buonasera, abbiamo ottenuto i certificati A1111EBITSRLXXXX_auth.pem e S1111EBITSRLXXXX_sign.pem. 
Quindi con il comando openssl pkcs12 - export -out S1111EBITSRLXXXX_sign.p12 -inkey EBIT_CER_SIGN.key - in S1111EBITSRLXXXX_sign.pem (analogamente per auth) abbiamo creato i certificati p12 con la chiave privata.
La chiave EBIT_CER_SIGN.key era stata generata con il comando:
openssl req -new -newkey rsa:2048 -nodes -keyout EBIT_CER_SIGN.key -out EBIT_CER_SIGN.csr

Abbiamo quindi inserito nella stessa cartella del file jwt-generator.jar i file p12 e pem e il data.json (tutti i file sono in allegato nello zip JTWEBIT.zip).

Il nostro problema è che il comando java -jar jwt-generator.jar -d data.json -a S1111EBITSRLXXXX_sign1.p12 -p dcmaet_sa1 -x
genera il seguente output:

Analyzing data

Issued At Time: Fri Feb 10 16:51:57 CET 2023
EXPiration time: Sat Feb 11 16:51:57 CET 2023
Private key NOT FOUNDED!
Public key founded.
Json data items founded: 18.

An error occur while trying to generate JWT, hope this can help:
EXCEPTION:
java.lang.IllegalArgumentException: Key argument cannot be null.
        at io.jsonwebtoken.lang.Assert.notNull(Assert.java:85)
        at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:106)
        at it.finanze.sanita.fjm.Launcher.generateAuthJWT(Launcher.java:285)
        at it.finanze.sanita.fjm.Launcher.buildToken(Launcher.java:180)
        at it.finanze.sanita.fjm.Launcher.main(Launcher.java:66)

Potete indicarci qual'è la soluzione?
Grazie mille

[JTWEBIT.zip](https://github.com/ministero-salute/it-fse-gtw-tools/files/10708988/JTWEBIT.zip)

**Comment by EbitFSE** [comment]
Buonasera, abbiamo risolto il problema sopra riportato. La chiave privata del certificato non veniva estratta prchè l'alias del certificato inserito nella riga di comando non era corretto.
Abbiamo visto che in questo modo generiamo i token usando uno dei due certificati (nel nostro caso quello che inizia per A1111.
Ci chiedevamo se il secondo certificato era da usare per la connessione HTTPS al gateway.
E' così?
Grazie

**Comment by EbitFSE** [comment]
Abbiamo risolto grazie
